version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: bmfc_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: binh_minh_fc
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - bmfc_network

volumes:
  mysql_dev_data:
    driver: local

networks:
  bmfc_network:
    driver: bridge
